### ISSUE TITLE
live deployment of the site

### ISSUE THREAD

**Issue by SubrataSarkar32** [ruppysuppy/Karmatek-2k20#1]
The site has been nicely built try testing it out by deploying it live at  [pythonanywhere.com](https://www.pythonanywhere.com/) (free deployment option). Also, you could send email confirmation mails using some mailing service or using Gmail smtp. Best of luck for testing it out @ruppysuppy !

**Comment by ruppysuppy** [comment]
> The site has been nicely built try testing it out by deploying it live at [pythonanywhere.com](https://www.pythonanywhere.com/) (free deployment option). Also, you could send email confirmation mails using some mailing service or using Gmail smtp. Best of luck for testing it out @ruppysuppy !

I am not going for live deployment, but thanks for the idea for confirmation email. I have implemented a basic prototype for it.
